# Generated by Django 4.0.4 on 2022-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=50)),
                ('alianza', models.CharField(max_length=50)),
                ('año_fundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('internacional', models.BooleanField()),
                ('año_inauguracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerolinea_nombre', models.CharField(max_length=50)),
                ('aerolinea_siglas', models.CharField(max_length=10)),
                ('vuelo_numero', models.IntegerField()),
                ('vuelo_siglas', models.CharField(max_length=15)),
                ('fecha_vuelo', models.DateField()),
                ('hora_vuelo', models.IntegerField()),
                ('aeropuerto_origen', models.CharField(max_length=5)),
                ('aeropuerto_destino', models.CharField(max_length=5)),
                ('duracion_vuelo', models.FloatField()),
            ],
        ),
    ]
