# Generated by Django 4.0.4 on 2022-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolineas', '0002_remove_vuelos_aerolinea_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='duracion_vuelo',
            field=models.IntegerField(),
        ),
    ]
