# Generated by Django 4.0.4 on 2022-05-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolineas', '0003_alter_vuelos_duracion_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='vuelo_numero',
            field=models.CharField(max_length=10),
        ),
    ]
