# Generated by Django 4.0.4 on 2022-05-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolineas', '0005_alter_aeropuertos_internacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
